spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/weixin_order_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

# 用xml文件代替
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: D:/IDEAWorkspace/sell/var/log/tomcat/
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wx4676b0351a113fd6
  mpAppSecret: fa475a6e0894fb42edea490ecaba205c
