spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/weixin_order_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell


# 用xml文件代替了，所以就不用这里的配置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: D:/IDEAWorkspace/sell/var/log/tomcat/
#  level:
#    com.imooc.LoggerTest: debug

#这是测试号的
wechat:
  mpAppId: wx944bee3c0903b94f
  mpAppSecret: d8503f7837f2e857cd96390507c9da93
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d86
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
